var firebaseConfig = {
    apiKey: "AIzaSyCW0Y881XfKogF4h7h9qIgP0iWw5PZ_hIU",
    authDomain: "db-primoffice-1b784.firebaseapp.com",
    databaseURL: "https://db-primoffice-1b784-default-rtdb.firebaseio.com",
    projectId: "db-primoffice-1b784",
    storageBucket: "db-primoffice-1b784.appspot.com",
    messagingSenderId: "265780957690",
    appId: "1:265780957690:web:9fa9725312f3f2cb41d443"
    };
    
    
    firebase.initializeApp(firebaseConfig)

    // Initialize Firebase
    
    
    var db = firebase.firestore();
    
    

    
    